apiVersion: v1beta3
kind: Pod
metadata:
    labels:
        name: benchmark
    name: benchmark-01
spec:
    containers:
      - name: benchmark
        image: quay.io/mikeln/twissandra_img:v9slim
        args: [ 'twiss-prod','bench' ]
        limits:
            cpu: 4
        ports:
          - name: cql
            containerPort: 9042
          - name: thrift
            containerPort: 9160
    volumes:
      - name: data
        emptyDir: {}
    restartPolicy: Never
