apiVersion: v1
kind: Pod
metadata:
    labels:
        name: benchmark
    name: benchmark-01
spec:
    containers:
      - name: benchmark
        image: 172.16.16.15:5000/twissandra_kub:v11slim
        args: [ 'twiss-prod','bench' ]
        limits:
            cpu: 4
        ports:
          - name: cql
            containerPort: 9042
          - name: thrift
            containerPort: 9160
    volumes:
      - name: data
        emptyDir: {}
    restartPolicy: Never
