id: datainject
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: datainject
    containers:
      - name: datainject
        image: mikeln/datainject-kub:v1
        ports:
          - name: cql
            containerPort: 9042
          - name: thrift
            containerPort: 9160
          - name: jmx
            containerPort: 7199
        env:
#          - key: MAX_HEAP_SIZE
#            value: 512M
#          - key: HEAP_NEWSIZE
#            value: 100M
          - key: KUBERNETES_API_PROTOCOL
            value: http
    volumes:
      - name: data
        source:
          emptyDir: {}
labels:
  name: datainject

    
