apiVersion: v1beta3
kind: Pod
metadata:
    labels:
        name: dataschema
    name: dataschema
spec:
    containers:
      - name: dataschema
        image: quay.io/mikeln/twissandra_kub:v11slim
        imagePullPolicy: IfNotPresent
        args: [ 'twiss-prod','db' ]
        limits:
            cpu: 1
        ports:
          - name: cql
            containerPort: 9042
          - name: thrift
            containerPort: 9160
    volumes:
      - name: data
        emptyDir: {}
    restartPolicy: Never
    
