apiVersion: v1
kind: Pod
metadata:
    name: dataschema
    namespace: cassandra
spec:
    containers:
      - name: dataschema
        image: quay.io/mikeln/twissandra_kub:v23slim
        imagePullPolicy: Always
        args: [ 'twiss-prod','db' ]
        ports:
          - name: cql
            containerPort: 9042
          - name: thrift
            containerPort: 9160
    volumes:
      - name: data
        emptyDir: {}
    restartPolicy: Never
    
