apiVersion: v1beta3
kind: Service
metadata:
    labels:
        name: twissandra
    name: twissandra
spec:
    ports:
        - name: webui
          port: 8222
    publicIPs: [ 172.16.1.103 ]
    selector:
        name: twissandra
