apiVersion: v1
kind: Service
metadata:
    labels:
        name: twissandra
    name: twissandra
    namespace: cassandra
spec:
    ports:
        - name: webui
          port: 8222
          targetPort: 30222
          nodePort: 30222
    selector:
        name: twissandra
    type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
        name: twissandra
    name: twissandra
    namespace: cassandra
spec:
    replicas: 1
    template:
      metadata:
          labels:
              name: twissandra
      spec:
          containers:
            - name: twissandra
              image: quay.io/mikeln/twissandra_kub:v23slim
              args: [ 'twiss-prod','app' ]
              ports:
                - name: web
                  containerPort: 8222
                - name: cql
                  containerPort: 9042
                - name: thrift
                  containerPort: 9160
              env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
