apiVersion: v1
kind: Pod
metadata:
    name: twissdebug
    namespace: cassandra
spec:
    containers:
      - name: twissdebug
        image: quay.io/mikeln/twissandra_kub:v23slim
        imagePullPolicy: Always
        args: [ 'twiss-prod','debug' ]
        ports:
          - name: cql
            containerPort: 9042
          - name: thrift
            containerPort: 9160
    volumes:
      - name: data
        emptyDir: {}
    restartPolicy: Never
    
